// <auto-generated />
namespace Ch7.R6.Library.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddYears : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddYears));
        
        string IMigrationMetadata.Id
        {
            get { return "201210110730223_AddYears"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
