// <auto-generated />
namespace Ch7.R6.Library.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ArtistCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArtistCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201209221819161_ArtistCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
