//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.R5.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Country = "\"USA\"";
            this.Provence = "\"New Jersey\"";
            this.City = "\"Paterson\"";
            this.ArtistSkills = new HashSet<ArtistSkill>();
        }
    
        public int ArtistId { get; set; }
        public string UserName { get; set; }
        public string Country { get; set; }
        public string Provence { get; set; }
        public string City { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<ArtistSkill> ArtistSkills { get; set; }
    }
}
