//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.R5.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistSkill
    {
        public ArtistSkill()
        {
            this.TalentName = "\"Guitar\"";
            this.SkillLevel = 0;
        }
    
        public int ArtistSkillId { get; set; }
        public string TalentName { get; set; }
        public int SkillLevel { get; set; }
        public string Details { get; set; }
        public string Styles { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
