//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch8.R7_4.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaylistModel", Namespace="http://schemas.datacontract.org/2004/07/WebAPIForLoadTest.Models")]
    [System.SerializableAttribute()]
    public partial class PlaylistModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayListNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ch8.R7_4.ServiceReference1.SongModel[] SongsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayListName {
            get {
                return this.PlayListNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayListNameField, value) != true)) {
                    this.PlayListNameField = value;
                    this.RaisePropertyChanged("PlayListName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ch8.R7_4.ServiceReference1.SongModel[] Songs {
            get {
                return this.SongsField;
            }
            set {
                if ((object.ReferenceEquals(this.SongsField, value) != true)) {
                    this.SongsField = value;
                    this.RaisePropertyChanged("Songs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SongModel", Namespace="http://schemas.datacontract.org/2004/07/WebAPIForLoadTest.Models")]
    [System.SerializableAttribute()]
    public partial class SongModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlbumNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PublishedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ch8.R7_4.ServiceReference1.ArtistModel SongArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SongOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlbumName {
            get {
                return this.AlbumNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumNameField, value) != true)) {
                    this.AlbumNameField = value;
                    this.RaisePropertyChanged("AlbumName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PublishedDate {
            get {
                return this.PublishedDateField;
            }
            set {
                if ((this.PublishedDateField.Equals(value) != true)) {
                    this.PublishedDateField = value;
                    this.RaisePropertyChanged("PublishedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ch8.R7_4.ServiceReference1.ArtistModel SongArtist {
            get {
                return this.SongArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.SongArtistField, value) != true)) {
                    this.SongArtistField = value;
                    this.RaisePropertyChanged("SongArtist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SongOrder {
            get {
                return this.SongOrderField;
            }
            set {
                if ((this.SongOrderField.Equals(value) != true)) {
                    this.SongOrderField = value;
                    this.RaisePropertyChanged("SongOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtistModel", Namespace="http://schemas.datacontract.org/2004/07/WebAPIForLoadTest.Models")]
    [System.SerializableAttribute()]
    public partial class ArtistModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistHomePageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistThumbnailImageUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistHomePageUrl {
            get {
                return this.ArtistHomePageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistHomePageUrlField, value) != true)) {
                    this.ArtistHomePageUrlField = value;
                    this.RaisePropertyChanged("ArtistHomePageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistName {
            get {
                return this.ArtistNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistNameField, value) != true)) {
                    this.ArtistNameField = value;
                    this.RaisePropertyChanged("ArtistName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistThumbnailImageUrl {
            get {
                return this.ArtistThumbnailImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistThumbnailImageUrlField, value) != true)) {
                    this.ArtistThumbnailImageUrlField = value;
                    this.RaisePropertyChanged("ArtistThumbnailImageUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPlaylistService")]
    public interface IPlaylistService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaylistService/GetPlayList", ReplyAction="http://tempuri.org/IPlaylistService/GetPlayListResponse")]
        Ch8.R7_4.ServiceReference1.PlaylistModel GetPlayList(int playlistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaylistService/GetPlayList", ReplyAction="http://tempuri.org/IPlaylistService/GetPlayListResponse")]
        System.Threading.Tasks.Task<Ch8.R7_4.ServiceReference1.PlaylistModel> GetPlayListAsync(int playlistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaylistService/GetAllPlayLists", ReplyAction="http://tempuri.org/IPlaylistService/GetAllPlayListsResponse")]
        Ch8.R7_4.ServiceReference1.PlaylistModel[] GetAllPlayLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlaylistService/GetAllPlayLists", ReplyAction="http://tempuri.org/IPlaylistService/GetAllPlayListsResponse")]
        System.Threading.Tasks.Task<Ch8.R7_4.ServiceReference1.PlaylistModel[]> GetAllPlayListsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlaylistServiceChannel : Ch8.R7_4.ServiceReference1.IPlaylistService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlaylistServiceClient : System.ServiceModel.ClientBase<Ch8.R7_4.ServiceReference1.IPlaylistService>, Ch8.R7_4.ServiceReference1.IPlaylistService {
        
        public PlaylistServiceClient() {
        }
        
        public PlaylistServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlaylistServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlaylistServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlaylistServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ch8.R7_4.ServiceReference1.PlaylistModel GetPlayList(int playlistId) {
            return base.Channel.GetPlayList(playlistId);
        }
        
        public System.Threading.Tasks.Task<Ch8.R7_4.ServiceReference1.PlaylistModel> GetPlayListAsync(int playlistId) {
            return base.Channel.GetPlayListAsync(playlistId);
        }
        
        public Ch8.R7_4.ServiceReference1.PlaylistModel[] GetAllPlayLists() {
            return base.Channel.GetAllPlayLists();
        }
        
        public System.Threading.Tasks.Task<Ch8.R7_4.ServiceReference1.PlaylistModel[]> GetAllPlayListsAsync() {
            return base.Channel.GetAllPlayListsAsync();
        }
    }
}
