//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.AlertSubscriptions = new HashSet<AlertSubscription>();
            this.ArtistBands = new HashSet<ArtistBand>();
            this.ArtistBlocks = new HashSet<ArtistBlock>();
            this.ArtistCollaborationSpaces = new HashSet<ArtistCollaborationSpace>();
            this.ArtistFavorites = new HashSet<ArtistFavorite>();
            this.ArtistSkills = new HashSet<ArtistSkill>();
            this.BandAuditions = new HashSet<BandAudition>();
            this.BandAuditionComments = new HashSet<BandAuditionComment>();
            this.CollaborationSpaceAlerts = new HashSet<CollaborationSpaceAlert>();
            this.CollaborationSpaceComments = new HashSet<CollaborationSpaceComment>();
            this.CollaborationSpaceInvites = new HashSet<CollaborationSpaceInvite>();
            this.Media = new HashSet<Medium>();
            this.PlayLists = new HashSet<PlayList>();
            this.Tasks = new HashSet<Task>();
            this.Messages = new HashSet<Message>();
            this.MessageRecipients = new HashSet<MessageRecipient>();
        }
    
        public int ArtistId { get; set; }
        public Nullable<System.Guid> OldUserId { get; set; }
        public string UserName { get; set; }
        public string Country { get; set; }
        public string Provence { get; set; }
        public string City { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string WebSite { get; set; }
        public byte ProfilePrivacyLevel { get; set; }
        public byte ContactPrivacyLevel { get; set; }
        public long ProfileViews { get; set; }
        public Nullable<System.DateTime> ProfileLastViewDate { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string AvatarURL { get; set; }
        public string EmailAddress { get; set; }
        public int FileUploadsInBytes { get; set; }
        public int FileUploadQuotaInBytes { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public bool ShowChatStatus { get; set; }
        public bool AllowChatSounds { get; set; }
    
        public virtual ICollection<AlertSubscription> AlertSubscriptions { get; set; }
        public virtual ICollection<ArtistBand> ArtistBands { get; set; }
        public virtual ICollection<ArtistBlock> ArtistBlocks { get; set; }
        public virtual ICollection<ArtistCollaborationSpace> ArtistCollaborationSpaces { get; set; }
        public virtual ICollection<ArtistFavorite> ArtistFavorites { get; set; }
        public virtual ICollection<ArtistSkill> ArtistSkills { get; set; }
        public virtual ICollection<BandAudition> BandAuditions { get; set; }
        public virtual ICollection<BandAuditionComment> BandAuditionComments { get; set; }
        public virtual ICollection<CollaborationSpaceAlert> CollaborationSpaceAlerts { get; set; }
        public virtual ICollection<CollaborationSpaceComment> CollaborationSpaceComments { get; set; }
        public virtual ICollection<CollaborationSpaceInvite> CollaborationSpaceInvites { get; set; }
        public virtual ICollection<Medium> Media { get; set; }
        public virtual ICollection<PlayList> PlayLists { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<MessageRecipient> MessageRecipients { get; set; }
        public virtual ArtistProfile ArtistProfile { get; set; }
    }
}
