//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistFavorite
    {
        public int ArtistFavoriteId { get; set; }
        public int ArtistId { get; set; }
        public string Title { get; set; }
        public Nullable<int> ItemId { get; set; }
        public int Category { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
