//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandAudition
    {
        public BandAudition()
        {
            this.BandAuditionComments = new HashSet<BandAuditionComment>();
        }
    
        public int BandAuditionId { get; set; }
        public int ProjectOpenPositionId { get; set; }
        public int ArtistId { get; set; }
        public int SongId { get; set; }
        public int VotesRequired { get; set; }
        public int VotesRecieved { get; set; }
        public string Status { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Song Song { get; set; }
        public virtual ICollection<BandAuditionComment> BandAuditionComments { get; set; }
    }
}
