//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaborationSpace
    {
        public CollaborationSpace()
        {
            this.ArtistCollaborationSpaces = new HashSet<ArtistCollaborationSpace>();
            this.CollaborationSpaceAlerts = new HashSet<CollaborationSpaceAlert>();
            this.CollaborationSpaceComments = new HashSet<CollaborationSpaceComment>();
            this.CollaborationSpaceFiles = new HashSet<CollaborationSpaceFile>();
            this.CollaborationSpaceGenres = new HashSet<CollaborationSpaceGenre>();
            this.CollaborationSpaceInvites = new HashSet<CollaborationSpaceInvite>();
            this.CollaborationSpaceMedias = new HashSet<CollaborationSpaceMedia>();
        }
    
        public int CollaborationSpaceId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool RestrictContributorsToBand { get; set; }
        public Nullable<int> BandId { get; set; }
        public bool AllowPublicView { get; set; }
        public byte CopyrightModel { get; set; }
        public bool AllowContributorsToPublish { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<System.DateTime> LastPostDate { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public int NumberViews { get; set; }
        public int NumberComments { get; set; }
        public CollaborationSpaceStatus Status { get; set; }
        public Nullable<int> ConceptId { get; set; }
        public string ConceptMediaType { get; set; }
    
        public virtual ICollection<ArtistCollaborationSpace> ArtistCollaborationSpaces { get; set; }
        public virtual Band Band { get; set; }
        public virtual ICollection<CollaborationSpaceAlert> CollaborationSpaceAlerts { get; set; }
        public virtual ICollection<CollaborationSpaceComment> CollaborationSpaceComments { get; set; }
        public virtual ICollection<CollaborationSpaceFile> CollaborationSpaceFiles { get; set; }
        public virtual ICollection<CollaborationSpaceGenre> CollaborationSpaceGenres { get; set; }
        public virtual ICollection<CollaborationSpaceInvite> CollaborationSpaceInvites { get; set; }
        public virtual ICollection<CollaborationSpaceMedia> CollaborationSpaceMedias { get; set; }
    }
}
