//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaborationSpaceGenre
    {
        public int CollaborationSpaceGenreId { get; set; }
        public int CollaborationSpaceId { get; set; }
        public int GenreLookUpId { get; set; }
    
        public virtual CollaborationSpace CollaborationSpace { get; set; }
        public virtual GenreLookUp GenreLookUp { get; set; }
    }
}
