//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaborationSpaceComment
    {
        public int CollaborationSpaceCommentId { get; set; }
        public int CollaborationSpaceID { get; set; }
        public int ArtistId { get; set; }
        public Nullable<int> CollabortationSpaceFileId { get; set; }
        public string CommentTitle { get; set; }
        public string CommentBody { get; set; }
        public int ThreadId { get; set; }
        public int ParentId { get; set; }
        public int NestLevel { get; set; }
        public string Path { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual CollaborationSpace CollaborationSpace { get; set; }
        public virtual CollaborationSpaceFile CollaborationSpaceFile { get; set; }
    }
}
