//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    
    public enum CollaborationSpaceStatus : byte
    {
        Recruiting = 0,
        Tracking = 1,
        TracksCompleted = 2,
        FinalReview = 3,
        Published = 4,
        OnHold = 5,
        Canceled = 6
    }
}
