//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenreLookUp
    {
        public GenreLookUp()
        {
            this.BandGenres = new HashSet<BandGenre>();
            this.CollaborationSpaceGenres = new HashSet<CollaborationSpaceGenre>();
        }
    
        public int GenreLookUpId { get; set; }
        public string GenreName { get; set; }
        public string Culture { get; set; }
    
        public virtual ICollection<BandGenre> BandGenres { get; set; }
        public virtual ICollection<CollaborationSpaceGenre> CollaborationSpaceGenres { get; set; }
    }
}
