//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageRecipient
    {
        public int MessageRecipientId { get; set; }
        public int MessageId { get; set; }
        public int ArtistId { get; set; }
        public bool MessageRead { get; set; }
        public short MessageStatus { get; set; }
        public string Folder { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual Artist Artist { get; set; }
    }
}
