//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.BandAuditions = new HashSet<BandAudition>();
            this.PlaylistItems = new HashSet<PlaylistItem>();
            this.SongComments = new HashSet<SongComment>();
        }
    
        public int SongId { get; set; }
        public int MediaId { get; set; }
        public string SongTitle { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public string ArtworkURL { get; set; }
        public string Lyrics { get; set; }
        public string SongDescription { get; set; }
        public string ActionParameter { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public Nullable<int> GenreId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool ShowInLibrary { get; set; }
    
        public virtual ICollection<BandAudition> BandAuditions { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual ICollection<PlaylistItem> PlaylistItems { get; set; }
        public virtual ICollection<SongComment> SongComments { get; set; }
    }
}
