// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Ch9.R3.Web.Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// ViewHomePage - Use 'ViewHomePageExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ViewHomePage()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIDemoWorldHomePageWinWindow.UIDemoWorldHomePageDocument.UIOuterContainerPane.UIItemCustom;
            HtmlCustom uISiteWelcomeCustom = this.UIDemoWorldHomePageWinWindow.UIDemoWorldHomePageDocument.UISiteWelcomeCustom;
            #endregion

            // Verify that the 'TagName' property of custom control equals 'HEADER'
            Assert.AreEqual(this.ViewHomePageExpectedValues.UIItemCustomTagName, uIItemCustom.TagName, "In correct value");

            // Verify that the 'Id' property of 'SiteWelcome' custom control equals 'SiteWelcome'
            Assert.AreEqual(this.ViewHomePageExpectedValues.UISiteWelcomeCustomId, uISiteWelcomeCustom.Id, "In correct text");
        }
        
        #region Properties
        public virtual ViewHomePageExpectedValues ViewHomePageExpectedValues
        {
            get
            {
                if ((this.mViewHomePageExpectedValues == null))
                {
                    this.mViewHomePageExpectedValues = new ViewHomePageExpectedValues();
                }
                return this.mViewHomePageExpectedValues;
            }
        }
        
        public UIDemoWorldHomePageWinWindow UIDemoWorldHomePageWinWindow
        {
            get
            {
                if ((this.mUIDemoWorldHomePageWinWindow == null))
                {
                    this.mUIDemoWorldHomePageWinWindow = new UIDemoWorldHomePageWinWindow();
                }
                return this.mUIDemoWorldHomePageWinWindow;
            }
        }
        #endregion
        
        #region Fields
        private ViewHomePageExpectedValues mViewHomePageExpectedValues;
        
        private UIDemoWorldHomePageWinWindow mUIDemoWorldHomePageWinWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ViewHomePage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class ViewHomePageExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'TagName' property of custom control equals 'HEADER'
        /// </summary>
        public string UIItemCustomTagName = "HEADER";
        
        /// <summary>
        /// Verify that the 'Id' property of 'SiteWelcome' custom control equals 'SiteWelcome'
        /// </summary>
        public string UISiteWelcomeCustomId = "SiteWelcome";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDemoWorldHomePageWinWindow : BrowserWindow
    {
        
        public UIDemoWorldHomePageWinWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Demo World Home Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Demo World Home Page");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIDemoWorldHomePageDocument UIDemoWorldHomePageDocument
        {
            get
            {
                if ((this.mUIDemoWorldHomePageDocument == null))
                {
                    this.mUIDemoWorldHomePageDocument = new UIDemoWorldHomePageDocument(this);
                }
                return this.mUIDemoWorldHomePageDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIDemoWorldHomePageDocument mUIDemoWorldHomePageDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDemoWorldHomePageDocument : HtmlDocument
    {
        
        public UIDemoWorldHomePageDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Demo World Home Page";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:37361/";
            this.WindowTitles.Add("Demo World Home Page");
            #endregion
        }
        
        #region Properties
        public UIOuterContainerPane UIOuterContainerPane
        {
            get
            {
                if ((this.mUIOuterContainerPane == null))
                {
                    this.mUIOuterContainerPane = new UIOuterContainerPane(this);
                }
                return this.mUIOuterContainerPane;
            }
        }
        
        public HtmlCustom UISiteWelcomeCustom
        {
            get
            {
                if ((this.mUISiteWelcomeCustom == null))
                {
                    this.mUISiteWelcomeCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUISiteWelcomeCustom.SearchProperties["Id"] = "SiteWelcome";
                    this.mUISiteWelcomeCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUISiteWelcomeCustom.SearchProperties["TagName"] = "ARTICLE";
                    this.mUISiteWelcomeCustom.FilterProperties["Class"] = null;
                    this.mUISiteWelcomeCustom.FilterProperties["ControlDefinition"] = "id=\"SiteWelcome\"";
                    this.mUISiteWelcomeCustom.FilterProperties["TagInstance"] = "1";
                    this.mUISiteWelcomeCustom.WindowTitles.Add("Demo World Home Page");
                    #endregion
                }
                return this.mUISiteWelcomeCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIOuterContainerPane mUIOuterContainerPane;
        
        private HtmlCustom mUISiteWelcomeCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIOuterContainerPane : HtmlDiv
    {
        
        public UIOuterContainerPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "OuterContainer";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "This is the news itemThis a summary of t";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"OuterContainer\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Demo World Home Page");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.SearchProperties["TagName"] = "HEADER";
                    this.mUIItemCustom.FilterProperties["Class"] = null;
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Demo World Home Page");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
}
