//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.R4.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTIST
    {
        public decimal ARTISTID { get; set; }
        public string USERNAME { get; set; }
        public string COUNTRY { get; set; }
        public string PROVENCE { get; set; }
        public string CITY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public decimal PROFILEPRIVACYLEVEL { get; set; }
        public decimal CONTACTPRIVACYLEVEL { get; set; }
        public decimal PROFILEVIEWS { get; set; }
    }
}
