// <auto-generated />
namespace Ch11.R3.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class refactor2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactor2));
        
        string IMigrationMetadata.Id
        {
            get { return "201211231509097_refactor2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
