// <auto-generated />
namespace Ch11.R3.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Rename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename));
        
        string IMigrationMetadata.Id
        {
            get { return "201301061533357_Rename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
