//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistBand
    {
        public int ArtistBandId { get; set; }
        public int ArtistId { get; set; }
        public Nullable<int> BandId { get; set; }
        public string Role { get; set; }
        public System.DateTime JoinedDate { get; set; }
        public bool IsActiveMember { get; set; }
        public Nullable<System.DateTime> DeactivateDate { get; set; }
        public bool AllowEditBand { get; set; }
        public bool IsMemberAdmin { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Band Band { get; set; }
    }
}
