//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Band
    {
        public Band()
        {
            this.ArtistBands = new HashSet<ArtistBand>();
            this.BandGenres = new HashSet<BandGenre>();
            this.CollaborationSpaces = new HashSet<CollaborationSpace>();
            this.PlayLists = new HashSet<PlayList>();
        }
    
        public int BandId { get; set; }
        public string BandName { get; set; }
        public string BandBio { get; set; }
        public string BandLogoUrl { get; set; }
        public string BandBackgroundImageUrl { get; set; }
        public string BandDisplayPhotoUrl { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<ArtistBand> ArtistBands { get; set; }
        public virtual ICollection<BandGenre> BandGenres { get; set; }
        public virtual ICollection<CollaborationSpace> CollaborationSpaces { get; set; }
        public virtual ICollection<PlayList> PlayLists { get; set; }
    }
}
