//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaborationSpaceFile
    {
        public CollaborationSpaceFile()
        {
            this.CollaborationSpaceComments = new HashSet<CollaborationSpaceComment>();
        }
    
        public int CollaborationSpaceFileId { get; set; }
        public int CollaborationSpaceId { get; set; }
        public int MediaId { get; set; }
        public string Description { get; set; }
        public int LikeCount { get; set; }
    
        public virtual CollaborationSpace CollaborationSpace { get; set; }
        public virtual ICollection<CollaborationSpaceComment> CollaborationSpaceComments { get; set; }
        public virtual Medium Medium { get; set; }
    }
}
