//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaborationSpaceMedia
    {
        public int CollaborationSpaceMediaId { get; set; }
        public int CollaborationSpaceId { get; set; }
        public int MediaId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Archive { get; set; }
    
        public virtual CollaborationSpace CollaborationSpace { get; set; }
        public virtual Medium Medium { get; set; }
    }
}
