//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public Medium()
        {
            this.CollaborationSpaceFiles = new HashSet<CollaborationSpaceFile>();
            this.CollaborationSpaceMedias = new HashSet<CollaborationSpaceMedia>();
            this.Songs = new HashSet<Song>();
        }
    
        public int MediaId { get; set; }
        public Nullable<int> ArtistId { get; set; }
        public string FriendlyFileName { get; set; }
        public string FileExtention { get; set; }
        public string LocalFilePath { get; set; }
        public string WebURL { get; set; }
        public bool IsCloudBlob { get; set; }
        public string AzureStorageContainer { get; set; }
        public string AzureBlobReferenceName { get; set; }
        public byte MediaType { get; set; }
        public int FileSizeInBytes { get; set; }
        public int BitRateInKbps { get; set; }
        public int AllowDownload { get; set; }
        public int DownloadCount { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsFileDeleted { get; set; }
        public string RIPEMD160Hash { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual ICollection<CollaborationSpaceFile> CollaborationSpaceFiles { get; set; }
        public virtual ICollection<CollaborationSpaceMedia> CollaborationSpaceMedias { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
    }
}
