//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch7.SharedAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongComment
    {
        public int SongCommentId { get; set; }
        public Nullable<int> SongId { get; set; }
        public string Comment { get; set; }
        public int Rating { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsApproved { get; set; }
        public bool IsAnonymous { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual Song Song { get; set; }
    }
}
